// utils/formatDataForExport.ts
import { SSIFormData, FormattedSSIFormData } from '@/app/interfaces';

export const formatDataForExport = (data: SSIFormData[]): FormattedSSIFormData => {
    return data.map((item) => ({
        patientName: item.patientName,
        age: item.age,
        gender: item.gender,
        dateOfAdmission: item.dateOfAdmission,
        dateOfProcedure: item.dateOfProcedure,
        admittingDepartment: item.admittingDepartment,
        departmentPrimarySurgeon: item.departmentPrimarySurgeon,
        procedureDoneBy: item.procedureDoneBy,
        procedureName: item.procedureName,
        diagnosis: item.diagnosis,
        otno: item.otno,
        outpatientProcedure: item.outpatientProcedure,
        scenarioOfProcedure: item.scenarioOfProcedure,
        woundClass: item.woundClass,
        papGiven: item.papGiven,
        papDuration: item.papDuration,
        ssiEventOccurred: item.ssiEventOccurred,
        dateOfSSIEvent: item.dateOfSSIEvent,
        microorganism1: item.microorganism1,
        antibioticPrescriptions: JSON.stringify(item.antibioticPrescriptions),
        timeOfInduction: item.timeOfInduction,
        timeOfSkinIncision: item.timeOfSkinIncision,
        timeOfEndSurgery: item.timeOfEndSurgery,
        isolate1: JSON.stringify(item.isolate1),
        isolate2: JSON.stringify(item.isolate2),
        symptomsDict: JSON.stringify(item.symptomsDict),
        SSIEvalCheckList: JSON.stringify(item.SSIEvalCheckList),
        specificEvent: item.specificEvent,
        organSpace: item.organSpace,
        detected: item.detected,
        status: item.status,
        patientId: item.patientId,
        microorganism2: item.microorganism2,
        secondaryBSIdeath: item.secondaryBSIdeath,
        antibioticGiven: item.antibioticGiven,
        // reviewedBy: item.reviewedBy,
        // reviewedAt: item.reviewedAt,
    }));
};